# Generated by Django 3.2.13 on 2022-05-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('base_experience', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
